version: 2.1

jobs:
  validate:
    docker:
      - image: circleci/openjdk:8u181
    steps:
      # restore cached dependencies? or at least gradle wrapper?
      - checkout
      - run: ./gradlew publishToMavenLocal

workflows:
  version: 2
  ci:
    jobs:
      - validate