version: 2.1

jobs:
  validate:
    docker:
      - image: circleci/openjdk:8u181
    steps:
      # restore cached dependencies? or at least gradle wrapper?
      - checkout
      - run: ./gradlew clean publishToMavenLocal

  release:
    docker:
      - image: circleci/openjdk:8u181
    steps:
      - checkout
      - run: ./gradlew assertIsRelease
      - run: ./gradlew handlePublications

  snapshot:
    docker:
      - image: circleci/openjdk:8u181
    steps:
      - checkout
      - run: ./gradlew assertIsSnapshot
      - run: ./gradlew handlePublications

workflows:
  version: 2
  main-workflow:
    jobs:
      - validate
      - release:
          type: approval
          requires:
            - validate
          filters:
            branches:
              only:
                - master
          context: JFrog
      - snapshot:
          requires:
            - validate
          context: JFrog
          filters:
            branches:
              only:
                - dev